[package]
name = "lgv"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
arrow = "49.0.0"
chrono = "0.4.34"
duckdb = "0.9.2"
half = "2.3.1"
log = "0.4.20"
memmap = "0.7.0"
uuid = "1.7.0"
zerocopy = "0.7.32"
