[package]
name = "lgv"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
arrow = "54.2.1"
chrono = "0.4.40"
duckdb = "1.2.1"
half = "2.5.0"
log = "0.4.26"
memmap = "0.7.0"
uuid = "1.16.0"
zerocopy = "0.8.23"
